export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const FETCH_FORM_DATA_SUCCESS = "FETCH_FORM_DATA_SUCCESS";
export const FETCH_FORM_DATA_ERROR = "FETCH_FORM_DATA_ERROR";
export const FETCH_FORM_DATA = "FETCH_FORM_DATA";
